global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: metric-aggregator
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']
  - job_name: 'ms-web'
    static_configs:
      - targets: ['ms-web:2019']
  - job_name: host-metric-agent
    static_configs:
      - targets: ['host-metric-agent:9100']
  - job_name: db-metric-agent
    static_configs:
      - targets: ['db-metric-agent:9187']
  - job_name: container-metric-agent
    static_configs:
      - targets: ['container-metric-agent:8080']
  - job_name: 'trace-aggregator'
    static_configs:
      - targets: [ 'trace-aggregator:3200' ]
