version: '3'

services:
  loki:
    container_name: loki
    image: grafana/loki:2.7.4
    ports:
      - 3100:3100
    networks:
      - default
    volumes:
      - ./etc/loki:/etc/loki
    command:
      - --config.file=/etc/loki/config.yml
    environment:
      TZ: $TZ
    restart: always
    cpu_count: 1
    mem_limit: 128M
    mem_reservation: 64M
networks:
  default:
    name: stack
    external: true
