apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: Loki
  - name: Tempo

datasources:
  - name: Metric aggregator (Prometheus)
    type: prometheus
    url: http://metric-aggregator:9090
    isDefault: true
    editable: false
  - name: Log aggregator (Loki)
    type: loki
    url: http://log-aggregator:3100
    editable: true
    jsonData:
      maxLines: 1000
  - name: Trace aggregator (Tempo)
    type: tempo
    access: proxy
    url: http://trace-aggregator:3200
    editable: true
