version: '3'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:9.4.7
    ports:
      - 3000:3000
    networks:
      - default
    secrets:
      - user_password
    volumes:
      - ./etc/grafana:/etc/grafana
      - ./var/lib/grafana:/var/lib/grafana
    environment:
      TZ: $TZ
      GF_DEFAULT_APP_MODE: $GRAFANA_APP_MODE
      GF_SECURITY_ADMIN_USER: $GRAFANA_USER
      GF_SECURITY_ADMIN_PASSWORD_FILE: /run/secrets/user_password
    restart: always
    cpu_count: 1
    mem_limit: 128M
    mem_reservation: 64M
networks:
  default:
    name: stack
    external: true
secrets:
  user_password:
    file: ./user_password.secret
