apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: false
  - name: Loki
    type: loki
    url: http://loki:3100
    editable: false
    jsonData:
      maxLines: 1000
