version: '3'

services:
  metric-aggregator:
    container_name: metric-aggregator
    image: prom/prometheus:v2.43.0
    ports:
      - 9090:9090
    networks:
      - default
    volumes:
      - ./etc/prometheus:/etc/prometheus
      - ./var/lib/prometheus:/var/lib/prometheus
      - ./prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/config.yml
    environment:
      TZ: $TZ
    restart: always
    cpu_count: 2
    mem_limit: 128M
    mem_reservation: 64M
networks:
  default:
    name: stack
    external: true
