version: '3'

services:
  supertokens-core:
    container_name: supertokens-core
    image: supertokens/supertokens-postgresql:4.4
    ports:
      - 3567:3567
    networks:
      - default
    secrets:
      - user_password
    environment:
      TZ: $TZ
      LOG_LEVEL: INFO
      POSTGRESQL_HOST: db
      POSTGRESQL_PORT: $DB_PORT
      POSTGRESQL_USER: $DB_USER
      POSTGRESQL_PASSWORD_FILE: /run/secrets/user_password
      POSTGRESQL_DATABASE_NAME: supertokens
      JVM_OPTS: -Xmx128m -Xms64m
    restart: always
    cpu_count: 2
    mem_limit: 128M
    mem_reservation: 64M
networks:
  default:
    name: stack
    external: true
secrets:
  user_password:
    file: ./user_password.secret
