version: '3'

services:
  db-metric-agent:
    container_name: db-metric-agent
    image: prometheuscommunity/postgres-exporter:v0.12.0
    expose:
      - 9187
    networks:
      - default
    secrets:
      - user_password
    environment:
      TZ: $TZ
      DATA_SOURCE_URI: db:$DB_PORT?sslmode=disable
      DATA_SOURCE_USER: $DB_USER
      DATA_SOURCE_PASS_FILE: /run/secrets/user_password
      PG_EXPORTER_AUTO_DISCOVER_DATABASES: 'true'
    restart: always
    cpu_count: 1
    mem_limit: 64M
    mem_reservation: 64M
networks:
  default:
    name: stack
    external: true
secrets:
  user_password:
    file: ./user_password.secret
